// <auto-generated />
using System;
using ExerciceContactApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciceContactApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExerciceContactApi.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://sm.ign.com/ign_fr/cover/a/avatar-gen/avatar-generations_bssq.jpg",
                            Birthdate = new DateTime(2002, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Babouche",
                            Fullname = "Babouche Mig",
                            Lastname = "Mig",
                            Sexe = "M"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://media.gqmagazine.fr/photos/63c9247a35fc113fac34f877/16:9/w_1280,c_limit/maxresdefault.jpg",
                            Birthdate = new DateTime(2002, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "King",
                            Fullname = "King Kong",
                            Lastname = "Kong",
                            Sexe = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
